[features]
seeds = false
skip-lint = false
[programs.localnet]
decentralized_stock_exchange = "43fWv3Y8kAkN7tnEDTVQwpWNqQt1ivpKsjbjHksu7kWz"

[programs.devnet]
decentralized_stock_exchange = "43fWv3Y8kAkN7tnEDTVQwpWNqQt1ivpKsjbjHksu7kWz"

[programs.testnet]
decentralized_stock_exchange = "43fWv3Y8kAkN7tnEDTVQwpWNqQt1ivpKsjbjHksu7kWz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/shree_kali/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
